// Codegen for type-safe i18n. Reads the canonical `en.json` locale and emits
// `src/i18n/generated.ts`, an interface mapping every flattened translation key
// to the params required by its `{{tokens}}`. Run via `pnpm gen:i18n`.
//
// The exported helpers are also imported by the i18n test suite so the freshness
// check uses the exact same generator the CLI does.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const TOKEN = /\{\{\s*(\w+)\s*\}\}/g

/** Returns the unique `{{token}}` names in a string, in first-seen order. */
export function extractTokens(value) {
  const seen = []
  for (const match of value.matchAll(TOKEN)) {
    if (!seen.includes(match[1])) seen.push(match[1])
  }
  return seen
}

/** Flattens a nested object of string leaves into sorted dot-path keys. */
export function flattenKeys(obj, prefix = '') {
  const keys = []
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key
    if (value !== null && typeof value === 'object') {
      keys.push(...flattenKeys(value, path))
    } else {
      keys.push(path)
    }
  }
  return keys.sort()
}

/** Resolves a dot-path key to its string value within a nested object. */
function valueAt(obj, key) {
  return key.split('.').reduce((node, part) => node[part], obj)
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/**
 * Emits a TypeScript property name: bare when it is a valid identifier, otherwise
 * a safely-escaped single-quoted literal. This keeps the output valid TS for keys
 * with dots/quotes/backslashes and for digit-leading interpolation tokens, and
 * matches biome's `asNeeded` quoting for identifier vs non-identifier names.
 */
function propertyName(name) {
  if (IDENTIFIER.test(name)) return name
  return `'${name.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/** Renders the params type for a translation value: empty -> Record<never, never>. */
function paramsType(value) {
  const tokens = extractTokens(value)
  if (tokens.length === 0) return 'Record<never, never>'
  return `{ ${tokens.map((t) => `${propertyName(t)}: string | number`).join('; ')} }`
}

/** Builds the full source of `generated.ts` from a parsed locale object. */
export function generateTypesSource(locale) {
  const entries = flattenKeys(locale).map(
    (key) => `  ${propertyName(key)}: ${paramsType(valueAt(locale, key))}`,
  )
  return `// AUTO-GENERATED by scripts/gen-i18n.mjs from src/locale/en.json. Do not edit.
// Run \`pnpm gen:i18n\` to regenerate.

export interface Translations {
${entries.join('\n')}
}
`
}

function main() {
  const here = dirname(fileURLToPath(import.meta.url))
  const source = resolve(here, '../src/locale/en.json')
  const target = resolve(here, '../src/i18n/generated.ts')
  const locale = JSON.parse(readFileSync(source, 'utf8'))
  writeFileSync(target, generateTypesSource(locale))
  console.log(`Wrote ${target}`)
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main()
}
