import { extractTokens, flattenKeys, generateTypesSource } from '@root/scripts/gen-i18n.mjs';

test('extractTokens finds unique tokens in first-seen order', () => {
  expect(extractTokens('Hi {{name}}, you have {{count}} of {{name}}')).toEqual(['name', 'count']);
});

test('extractTokens returns an empty array when there are no tokens', () => {
  expect(extractTokens('plain text')).toEqual([]);
});

test('flattenKeys returns dot-paths sorted alphabetically', () => {
  expect(flattenKeys({ general: { ok: 'OK' }, app: { title: 'T' } })).toEqual([
    'app.title',
    'general.ok',
  ]);
});

test('generateTypesSource emits a typed interface entry per key', () => {
  const src = generateTypesSource({
    general: { buttons: { ok: 'OK' }, greeting: 'Hi {{name}}' },
  });
  expect(src).toBe(
    `// AUTO-GENERATED by scripts/gen-i18n.mjs from src/locale/en.json. Do not edit.
// Run \`pnpm gen:i18n\` to regenerate.

export interface Translations {
  'general.buttons.ok': Record<never, never>
  'general.greeting': { name: string | number }
}
`,
  );
});

test('generateTypesSource lists multiple params separated by semicolons', () => {
  // Top-level identifier key is emitted unquoted (biome-canonical asNeeded quoting).
  const src = generateTypesSource({ greeting: 'Hi {{name}}, you are {{age}}' });
  expect(src).toContain('greeting: { name: string | number; age: string | number }');
});

test('quotes digit-leading interpolation tokens so the output stays valid TS', () => {
  const src = generateTypesSource({ greeting: 'Hi {{1st}} and {{value}}' });
  expect(src).toContain("'1st': string | number; value: string | number");
});

test('escapes keys that contain quotes or backslashes', () => {
  const src = generateTypesSource({ "it's": 'x' });
  expect(src).toContain("'it\\'s': Record<never, never>");
});

test('leaves a top-level identifier key unquoted (biome-canonical)', () => {
  const src = generateTypesSource({ title: 'x' });
  expect(src).toContain('\n  title: Record<never, never>');
});
