// AUTO-GENERATED by scripts/gen-i18n.mjs from src/locale/en.json. Do not edit.
// Run `pnpm gen:i18n` to regenerate.

export interface Translations {
  'app.title': Record<never, never>
  'general.buttons.ok': Record<never, never>
  'general.buttons.startCheck': Record<never, never>
  'general.someInterpolatedValue': { value: string | number }
}
